version: '3'

services:
    waf:
        image: owasp/modsecurity:3
        depends_on:
            - web
            - web1
            - db
        volumes:
            - ./waf_3/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
            - ./waf_3/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./waf_3/nginx_conf/modsecurity.conf:/etc/conf.d/modsecurity.conf
            - ./waf_3/modsecurity_conf/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
            - ./waf_3/modsecurity_conf/setup.conf:/etc/modsecurity.d/setup.conf
            - ./waf_3/modsecurity-crs/:/usr/local/modsecurity-crs/
            - ./waf_3/403/403.html:/usr/share/nginx/html/403.html
            - ./log/modsec_audit.log:/var/log/modsec_audit.log
        ports:
            - 80:80
    web:
        build:
            context: ./App1
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./App1/:/var/www/html/
    web1:
        build:
            context: ./App2
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./App2/:/var/www/html/
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./database/:/var/lib/mysql
            - ./App1/test_data.sql:/home/test_data.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass