apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: webapp_database
        - name: MYSQL_USER
          value: ledung
        - name: MYSQL_PASSWORD
          value: ledung362
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume-claim
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume-claim
        persistentVolumeClaim:
          claimName: mysql-volume-claim