apiVersion: v1
kind: Service
metadata:
  name: modsecurity-service
  labels:
    tier: backend
spec:
  selector:
    app: modsecurity
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  externalIPs:
  - 172.104.173.37
  type: LoadBalancer