apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: php-code
        persistentVolumeClaim:
          claimName: php-volume-claim
      containers:
      - name: php
        image: php:7.4-fpm
        volumeMounts:
        - name: php-code
          mountPath: /code
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: php-code
          mountPath: /code
        command:
        - wget
        - "-O"
        - "/code/index.php"
        - https://raw.githubusercontent.com/do-community/php-kubernetes/master/index.php