apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: php-volume-claim
      containers:
      - name: php
        image: ledungdocker/php7.4-fpm:latest
        volumeMounts:
        - name: code
          mountPath: /code